@startuml class
interface Expression
abstract BinaryOperator

Calculator *-- Expression
Expression <|-- BinaryOperator
Expression <|-- Value
Expression <|-- Variable
package arithmetic {
    BinaryOperator <|-- Add
    BinaryOperator <|-- Substract
    BinaryOperator <|-- Multiply
    BinaryOperator <|-- Divide
}
package assignment {
    BinaryOperator <|-- SimpleAssign
}
@enduml