@startuml class
package domain {
    interface Expression
    Expression <|-- Value
    Expression <|-- Variable
}
package operator {
    abstract BinaryOperator
    Expression <|-- BinaryOperator
    package arithmetic {
        BinaryOperator <|-- Add
        BinaryOperator <|-- Substract
        BinaryOperator <|-- Multiply
        BinaryOperator <|-- Divide
    }
    package assignment {
        BinaryOperator <|-- SimpleAssign
    }
}
package request {
    CalculatorRequest *-- CalculatorValidRequest
    CalculatorRequest *-- CalculatorInValidRequest
}
Calculator *-- Expression
Calculator *-- CalculatorValidRequest


@enduml